export enum Role {
  EMPLOYEE = 'EMPLOYEE',
  MANAGER = 'MANAGER',
  HR = 'HR',
}

export enum LeaveTypeCode {
  CL = 'CL',
  SL = 'SL',
  EL = 'EL',
}

export enum LeaveStatus {
  DRAFT = 'DRAFT',
  PENDING_MANAGER = 'PENDING_MANAGER',
  PENDING_HR = 'PENDING_HR',
  ESCALATED = 'ESCALATED',
  APPROVED = 'APPROVED',
  REJECTED_BY_MANAGER = 'REJECTED_BY_MANAGER',
  REJECTED_BY_HR = 'REJECTED_BY_HR',
  CANCELLED = 'CANCELLED',
}

export enum AuditAction {
  LEAVE_CREATED = 'LEAVE_CREATED',
  LEAVE_SUBMITTED = 'LEAVE_SUBMITTED',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  MANAGER_REJECTED = 'MANAGER_REJECTED',
  HR_APPROVED = 'HR_APPROVED',
  HR_REJECTED = 'HR_REJECTED',
  LEAVE_CANCELLED = 'LEAVE_CANCELLED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  ATTACHMENT_UPLOADED = 'ATTACHMENT_UPLOADED',
  REMINDER_SENT = 'REMINDER_SENT',
  ESCALATED = 'ESCALATED',
}
